# Generated by Django 4.1 on 2023-09-13 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeetingRoom",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="会议室id",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="会议室")),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("name", models.CharField(max_length=32, verbose_name="用户姓名")),
                (
                    "id",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="学工号",
                    ),
                ),
                ("password", models.CharField(max_length=32, verbose_name="密码")),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "useto",
                    models.IntegerField(
                        choices=[(1, "教学"), (2, "会议"), (3, "讲座"), (4, "答辩")],
                        verbose_name="用途",
                    ),
                ),
                ("booking_date", models.DateField(verbose_name="预定日期")),
                (
                    "booking_time",
                    models.IntegerField(
                        choices=[
                            (1, "8:00"),
                            (2, "8:30"),
                            (3, "9:00"),
                            (4, "9:30"),
                            (5, "10:00"),
                            (6, "10:30"),
                            (7, "11:00"),
                            (8, "11:30"),
                            (9, "12:00"),
                            (10, "12:30"),
                            (11, "13:00"),
                            (12, "13:30"),
                            (13, "14:00"),
                            (14, "14:30"),
                            (15, "15:00"),
                            (16, "15:30"),
                            (17, "16:00"),
                            (18, "16:30"),
                            (19, "17:00"),
                            (20, "17:30"),
                            (21, "18:00"),
                            (22, "18:30"),
                            (23, "19:00"),
                            (24, "19:30"),
                            (25, "20:00"),
                            (26, "20:30"),
                            (27, "21:00"),
                            (28, "21:30"),
                            (29, "22:00"),
                            (30, "22:30"),
                        ],
                        verbose_name="预定时间段",
                    ),
                ),
                (
                    "ending_time",
                    models.IntegerField(
                        choices=[
                            (1, "8:00"),
                            (2, "8:30"),
                            (3, "9:00"),
                            (4, "9:30"),
                            (5, "10:00"),
                            (6, "10:30"),
                            (7, "11:00"),
                            (8, "11:30"),
                            (9, "12:00"),
                            (10, "12:30"),
                            (11, "13:00"),
                            (12, "13:30"),
                            (13, "14:00"),
                            (14, "14:30"),
                            (15, "15:00"),
                            (16, "15:30"),
                            (17, "16:00"),
                            (18, "16:30"),
                            (19, "17:00"),
                            (20, "17:30"),
                            (21, "18:00"),
                            (22, "18:30"),
                            (23, "19:00"),
                            (24, "19:30"),
                            (25, "20:00"),
                            (26, "20:30"),
                            (27, "21:00"),
                            (28, "21:30"),
                            (29, "22:00"),
                            (30, "22:30"),
                        ],
                        verbose_name="结束时间段",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.meetingroom",
                        verbose_name="会议室",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.userinfo",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "unique_together": {("booking_date", "booking_time", "room")},
            },
        ),
    ]
