# Generated by Django 4.1 on 2023-09-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_booking_mae_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="username",
            field=models.CharField(default=1, max_length=32, verbose_name="用户名称"),
            preserve_default=False,
        ),
    ]
