# Generated by Django 4.1 on 2023-09-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_booking_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="roomname",
            field=models.CharField(default=1, max_length=32, verbose_name="会议室名称"),
            preserve_default=False,
        ),
    ]
