# Generated by Django 4.1 on 2023-09-14 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_booking_roomname"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
    ]
